sudo: false
language: node_js
node_js:
  - 4
  - 5
  - 6

before_script:
  - npm install -g firebase-tools

script:
  - npm test
  - npm run build

after_script:
  - npm run coveralls

after_success:
  firebase deploy --token "$FIREBASE_TOKEN"